# Numpy: Package for Multidimensional array
## Vector(1d)
### Matrix(2d or 1d)

In [8]:
import numpy as np

In [7]:
simple_list=[6,7,9]
np.array(simple_list)    #converts list to array

array([6, 7, 9])

In [5]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [10]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(5,30)     #gives range from 5 to 30. last arg is not included

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [7]:
np.arange(5,30,2)   #gives range from 5 to 30 in steps of 2

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [11]:
np.zeros(5)      #gives 5 zero's in float

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

In [9]:
np.ones((2,5))       #gives matrix of 2 rows, 5 columns of float 1.0

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.linspace(0,20,10)       #gives 10 random no's between 0 and 20 including 0 and 20

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [19]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [23]:
np.eye(5)        #matrix of 5x5 with 1.0 as diagonal element

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(2)      #two values between 0-1 in list. (uniform distribution)

array([0.94241244, 0.86233955])

In [24]:
np.random.rand(2,4)       #2x4 matrix of values between 0-1 (uniform distribution)

array([[0.2825951 , 0.75179098, 0.3143079 , 0.63212069],
       [0.78636512, 0.19451472, 0.4886957 , 0.03226591]])

In [20]:
np.random.rand(2,7)

array([[0.60449972, 0.94172166, 0.16864736, 0.66228363, 0.48680831,
        0.96392001, 0.86241484],
       [0.60660465, 0.95392168, 0.18093113, 0.83750959, 0.33495565,
        0.5723394 , 0.67642657]])

In [36]:
np.random.randint(2,10)  #gives random integer between 2 and 10 excluding 10

7

In [41]:
np.random.randint(20,30,10)   #gives random 10 integers as list between 20 and 30. excluding 30

array([21, 27, 20, 26, 20, 23, 25, 27, 24, 26])

In [80]:
rand_array = np.random.randint(0,100,20)
rand_array

array([76, 16, 10, 30, 83,  3, 45, 12, 92,  3, 23, 58, 45, 43, 78, 63, 62,
       72, 20, 66])

In [72]:
rand_array.max()   #gives maximum number from array

92

In [73]:
rand_array.min()

2

In [75]:
rand_array.argmax()  #returns index position of maximum number in array.

4

In [76]:
rand_array.argmin()  #returns index position of minimum number in array.

11

In [96]:
sample_array = np.arange(20)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [97]:
sample_array.reshape(4,5)          #convers sample_array into a list of 4 lists of 5 numbers in it. (4x5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [99]:
sample_array.shape       #returns the no of elements in sample

(20,)

In [90]:
sample_array.dtype      #returns data type of sample

dtype('int32')

In [109]:
a = np.random.rand(2,3)
a

array([[0.58268244, 0.60851803, 0.7155438 ],
       [0.5505222 , 0.56626154, 0.55039724]])

In [110]:
a.T     #returns transpose of a1

array([[0.58268244, 0.5505222 ],
       [0.60851803, 0.56626154],
       [0.7155438 , 0.55039724]])

In [132]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [125]:
sample_array[8]     #returns no at index position 8

18

In [126]:
sample_array[2:5]

array([12, 13, 14])

In [127]:
sample_array[[2,5]]   #gives no at idx 2 and 5

array([12, 15])

In [134]:
sample_array[1:4] = 100
sample_array       

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [140]:
sample_array = np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [141]:
subset_sample_array = sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [142]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

### Two-Dimensional array

In [143]:
sample_matrix = np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [144]:
sample_matrix[0][2]

1

In [145]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [146]:
sample_matrix[2]

array([56, 76, 24,  7])

### Custom indexing

In [147]:
sample_matrix = np.array(([30,10,1,23],[24,21,32,33],[6,76,24,7]))
sample_matrix

array([[30, 10,  1, 23],
       [24, 21, 32, 33],
       [ 6, 76, 24,  7]])

In [152]:
sample_matrix[: , (2,3)]    #returns elements at 2nd and 3rd idx position of each list

array([[ 1, 23],
       [32, 33],
       [24,  7]])

In [154]:
sample_matrix[1:, (1,2,3)]

array([[21, 32, 33],
       [76, 24,  7]])

###  Selection techniques

In [10]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [11]:
bool=sample_array<10
bool

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [12]:
sample_array[bool]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [14]:
np.exp(sample_array)  #returns e to the power (nuber from sample)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [15]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [16]:
np.log(sample_array)     #natural log

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [17]:
np.max(sample_array)       #max no from sample

30

In [18]:
np.min(sample_array)      #min no from sample

1

In [19]:
np.argmax(sample_array)   #index position of max no

29

In [20]:
np.argmin(sample_array)   #index position of min no

0

In [21]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [22]:
np.std(sample_array)        #standard deviation

8.65544144839919

In [23]:
np.var(sample_array)        #variance

74.91666666666667

In [24]:
np.mean(sample_array)       #mean / average

15.5

In [25]:
array=np.random.randn(2,2)    #2x2 matrix of random floats
array

array([[-0.68134835, -0.07359109],
       [-1.21807941,  0.3359086 ]])

In [26]:
np.round(array,decimals=2)

array([[-0.68, -0.07],
       [-1.22,  0.34]])

In [27]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)        #removes duplicate

array(['cricket', 'fball', 'golf'], dtype='<U7')

In [28]:
import pandas as pd

In [34]:
labels=['w','x','y','z']

list=[10,20,30,40]

array=np.array([10,20,30,40])

dict={'w':10,'x':20,'y':30,'z':40}

In [35]:
pd.Series(data=list)

0    10
1    20
2    30
3    40
dtype: int64

In [36]:
pd.Series(data=list,index=labels)

w    10
x    20
y    30
z    40
dtype: int64

In [42]:
pd.Series(data=labels, index=array)

10    w
20    x
30    y
40    z
dtype: object

In [44]:
pd.Series(dict)

w     1
x    20
y    30
z    40
dtype: int64

### Pandas dataframe and indexing

In [75]:
sports1 = pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [76]:
sports1['cricket']

1

In [77]:
sports2 = pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [78]:
sports1+sports2       #since baseball and basketball are not common, their data is NaN (Not a Number)

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [ ]:
# we can create data frames using DataFrame in pandas.

In [122]:
df1 = pd.DataFrame(np.random.randn(8,5), index='A B C D E F G H '.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

# here we are creating a dataframe having ABCDEFGH as index and columns as scores.
# remember matrix dimension should match the no of index and columns. Here 8 rows ie index and 5 columns ie scores

Score1    Score2    Score3    Score4    Score5
A -0.796169 -0.016487  0.661867 -0.790941  0.911580
B  0.066180  0.966134 -0.083249  0.641596  0.161055
C -0.037802 -1.465854 -1.160520  0.366560 -0.289925
D -1.428743  1.556152  0.158617 -0.297140 -0.886973
E  0.945872  0.750524  0.231879 -0.301325  0.071591
F -0.329936  0.147320  1.191657 -1.254765  0.301807
G -0.925759  0.561737 -1.044122 -0.425101  0.263567
H  2.852111 -0.008093 -0.934717 -1.133683 -0.608650

In [123]:
df1['Score1']   #we can access particular score

A   -0.796169
B    0.066180
C   -0.037802
D   -1.428743
E    0.945872
F   -0.329936
G   -0.925759
H    2.852111
Name: Score1, dtype: float64

In [124]:
df1[['Score2','Score1']]

Score2    Score1
A -0.016487 -0.796169
B  0.966134  0.066180
C -1.465854 -0.037802
D  1.556152 -1.428743
E  0.750524  0.945872
F  0.147320 -0.329936
G  0.561737 -0.925759
H -0.008093  2.852111

In [125]:
df1['Score5'] = df1['Score1'] + df1['Score2']  #we can reassign values of columns
df1

Score1    Score2    Score3    Score4    Score5
A -0.796169 -0.016487  0.661867 -0.790941 -0.812656
B  0.066180  0.966134 -0.083249  0.641596  1.032314
C -0.037802 -1.465854 -1.160520  0.366560 -1.503655
D -1.428743  1.556152  0.158617 -0.297140  0.127409
E  0.945872  0.750524  0.231879 -0.301325  1.696396
F -0.329936  0.147320  1.191657 -1.254765 -0.182616
G -0.925759  0.561737 -1.044122 -0.425101 -0.364021
H  2.852111 -0.008093 -0.934717 -1.133683  2.844018

In [149]:
df1['Score6'] = 1 + df1['Score1']  #we can add new columns
df1

Score1    Score2    Score3    Score4    Score5    Score6
A -0.796169 -0.016487  0.661867 -0.790941 -0.812656  0.203831
B  0.066180  0.966134 -0.083249  0.641596  1.032314  1.066180
C -0.037802 -1.465854 -1.160520  0.366560 -1.503655  0.962198
D -1.428743  1.556152  0.158617 -0.297140  0.127409 -0.428743
E  0.945872  0.750524  0.231879 -0.301325  1.696396  1.945872
F -0.329936  0.147320  1.191657 -1.254765 -0.182616  0.670064
G -0.925759  0.561737 -1.044122 -0.425101 -0.364021  0.074241
H  2.852111 -0.008093 -0.934717 -1.133683  2.844018  3.852111

In [144]:
df1.drop('Score5', axis=1)  #we can delete a column using drop(). axis=1 for column and axis=0 for rows

Score1    Score2    Score3    Score4    Score6
A -0.796169 -0.016487  0.661867 -0.790941  0.203831
B  0.066180  0.966134 -0.083249  0.641596  1.066180
C -0.037802 -1.465854 -1.160520  0.366560  0.962198
D -1.428743  1.556152  0.158617 -0.297140 -0.428743
E  0.945872  0.750524  0.231879 -0.301325  1.945872
F -0.329936  0.147320  1.191657 -1.254765  0.670064
G -0.925759  0.561737 -1.044122 -0.425101  0.074241
H  2.852111 -0.008093 -0.934717 -1.133683  3.852111

In [145]:
df1.drop('A', axis=0)    #default value of axis is 0 ie rows

Score1    Score2    Score3    Score4    Score5    Score6
B  0.066180  0.966134 -0.083249  0.641596  1.032314  1.066180
C -0.037802 -1.465854 -1.160520  0.366560 -1.503655  0.962198
D -1.428743  1.556152  0.158617 -0.297140  0.127409 -0.428743
E  0.945872  0.750524  0.231879 -0.301325  1.696396  1.945872
F -0.329936  0.147320  1.191657 -1.254765 -0.182616  0.670064
G -0.925759  0.561737 -1.044122 -0.425101 -0.364021  0.074241
H  2.852111 -0.008093 -0.934717 -1.133683  2.844018  3.852111

In [150]:
df1      #adding a column mutates a dataframe but dropping doesn't. We can still see 'A' row and 'Score5' column in orginal df1

Score1    Score2    Score3    Score4    Score5    Score6
A -0.796169 -0.016487  0.661867 -0.790941 -0.812656  0.203831
B  0.066180  0.966134 -0.083249  0.641596  1.032314  1.066180
C -0.037802 -1.465854 -1.160520  0.366560 -1.503655  0.962198
D -1.428743  1.556152  0.158617 -0.297140  0.127409 -0.428743
E  0.945872  0.750524  0.231879 -0.301325  1.696396  1.945872
F -0.329936  0.147320  1.191657 -1.254765 -0.182616  0.670064
G -0.925759  0.561737 -1.044122 -0.425101 -0.364021  0.074241
H  2.852111 -0.008093 -0.934717 -1.133683  2.844018  3.852111

In [136]:
df1.reset_index()     #this converts the existing index into a column and new index is set as sequential no.

index    Score1    Score2    Score3    Score4    Score5    Score6
0     A -0.796169 -0.016487  0.661867 -0.790941 -0.812656  0.203831
1     B  0.066180  0.966134 -0.083249  0.641596  1.032314  1.066180
2     C -0.037802 -1.465854 -1.160520  0.366560 -1.503655  0.962198
3     D -1.428743  1.556152  0.158617 -0.297140  0.127409 -0.428743
4     E  0.945872  0.750524  0.231879 -0.301325  1.696396  1.945872
5     F -0.329936  0.147320  1.191657 -1.254765 -0.182616  0.670064
6     G -0.925759  0.561737 -1.044122 -0.425101 -0.364021  0.074241
7     H  2.852111 -0.008093 -0.934717 -1.133683  2.844018  3.852111

In [59]:
df2 = {'ID':['101','102','103','107','176'],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df = pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavin      87
4  176  Lally     123

In [155]:
new = pd.DataFrame([('bird', 100),('mammal', 50)], ['crow','monkey'],['species','speed'])
new

species  speed
crow      bird    100
monkey  mammal     50